security:

    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory: { memory: ~ }

        wsse:
            entity: { class: App:User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        wsse_secured:
            pattern: ^/
            form_login:
                provider:    wsse
                csrf_token_generator: security.csrf.token_manager
                login_path:  admin_login
                check_path:  admin_login_check
                default_target_path: index
            logout:
                path:        admin_logout
                target:      admin_login
            anonymous:  true #true
            security:   true
            stateless:  false

        main:
            anonymous: true

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/index, roles: ROLE_ADMIN }
