<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUmiwEd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUmiwEd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPUmiwEd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPUmiwEd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPUmiwEd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PUmiwEd',
    'container.build_id' => '9efa2e61',
    'container.build_time' => 1524559025,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUmiwEd');
